title: LinuxOps
url: 'https://LinuxOps.co.uk/'
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:
logo: /siteicon.png
description: DevOps Culture
author:
  name: Sherif Moneim
  email: sherif@hosty.uk
  twitter: ZeroDeth
social:
  name: Base Template
  links:
    - 'https://github.com/CloudCannon/base-jekyll-template'
permalink: '/:categories/:title/'
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
collections:
  sets:
jekyll-archives:
  enabled:
    - categories
defaults:
  - scope:
      path:
    values:
      layout: default
  - scope:
      type:
    values:
      layout: post
      comments: true
  - scope:
      type:
    values:
      _hide_content: true
  - scope:
      path: index.html
    values:
      body_class: show_hero_search
social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS
types:
  - Document
  - Video
_comments: